### ISSUE TITLE
style not applied without ::shadow

### ISSUE THREAD

**Issue by prompteus** [StartPolymer/s-svg#1]
Styles weren't applied using this code:
```
path {
	stroke: black;
	fill: transparent;
	stroke-width: 1px;
	vector-effect: non-scaling-stroke;
}
```

When I used classes like shown in README like this:
```
.icon {
	stroke: black;
	fill: transparent;
	stroke-width: 1px;
	vector-effect: non-scaling-stroke;
}
<s-svg class="icon" src="..."></s-svg>
```
It partially worked. Stroke, fill and stroke-width were applied, but vector-effect wasn't.

However, I got it working using ::shadow pseudo-element:
```
::shadow path {
	stroke: black;
	fill: transparent;
	stroke-width: 1px;
	vector-effect: non-scaling-stroke;
}
```

Polymer version: 1.7.1
Tested in browsers: Chrome, Safari on Mac OS Sierra

**Comment by prompteus** [comment]
It's also worth noting that ::shadow pseudo element is considered as deprecated as of now.

I'm now sure what you can do about this whole thing, but you could at least update the README.

**Comment by JosefJezek** [comment]
@cuddlecheek I added mixin for path, try use
```css
--s-svg-path: {
  stroke: black;
  fill: transparent;
  stroke-width: 1px;
  vector-effect: non-scaling-stroke;
};
```
